
name: lz - platform-management-test

on:
  push:
    paths:
      - 'parameters/platform-management-test.json'

  workflow_dispatch:

  pull_request_target:
    types:
      - closed
    paths:
      - 'parameters/platform-management-test.json'

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') ||
         github.event.pull_request.merged == true
    uses: gazelle-cloud/azurePlatform/.github/workflows/template-Landingzone.yml@main
    with:
      managementGroupName : platform
      managementGroupHierarchy: test
      parameterFile: ./parameters/platform-management-test.json
      mainBicep: ./azurePlatform/Landingzone/bicep/main.bicep
    secrets: inherit
