
name: lz - replaceMe-lz-landingzoneName

on:
  push:
    paths:
      - 'parameters/replaceMe-lz-landingzoneName.json'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: gazelle-cloud/azurePlatform/.github/workflows/template-Landingzone.yml@main
    with:
      managementGroupName : replaceMe-lz-managementGroupName
      managementGroupHierarchy: replaceMe-lz-managementGroupHierarchy
      location: replaceMe-lz-location
      parameterFile: ./parameters/replaceMe-lz-landingzoneName.json
      mainBicep: ./azurePlatform/Landingzone/bicep/main.bicep
    secrets: inherit
