
name: lz - replaceMe-lz-landingzoneName

on:
  push:
    paths:
      - 'parameters/replaceMe-lz-landingzoneName.json'

  workflow_dispatch:

  pull_request_target:
    types:
      - closed
    paths:
      - 'parameters/replaceMe-lz-landingzoneName.json'

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') || 
         github.event.pull_request.merged == true
    uses: gazelle-cloud/azurePlatform/.github/workflows/template-Landingzone.yml@main
    with:
      managementGroupName : replaceMe-lz-managementGroupName
      managementGroupHierarchy: replaceMe-lz-managementGroupHierarchy
      parameterFile: ./parameters/replaceMe-lz-landingzoneName.json
      mainBicep: ./azurePlatform/Landingzone/bicep/main.bicep
    secrets: inherit
